apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: magiccap-upload-proxy-prod-letsencrypt
spec:
  secretName: magiccap-upload-proxy-prod-letsencrypt
  dnsNames:
  - proxy.magiccap.me
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - proxy.magiccap.me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
